# -*- coding: utf-8 -*-
"""3D House_copy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cKEyhNXqVA-j1J0kk7CXqexRy4z1kJ3Q
"""

import requests
import pandas as pd
import numpy as np
from urllib.request import urlopen
from zipfile import ZipFile
from zipfile import *
from io import BytesIO
from google.colab import drive
drive.mount('/content/gdrive')

print('Downloading started')
url = f'https://downloadagiv.blob.core.windows.net/dhm-vlaanderen-ii-dsm-raster-1m/DHMVIIDSMRAS1m_k43.zip'

# Downloading the file by sending the request to the URL
req = requests.get(url)
filename = url.split('/')[-1]
print('Downloading Completed')
zipfile= ZipFile(BytesIO(req.content))

listOfFileNames = zipfile.namelist()
for filename in listOfFileNames:
  if filename.endswith('.tif'):
    zipfile.extract(filename, '/content/gdrive/MyDrive')

#!pip install rasterio
#import rasterio

import rasterio
import os
from google.colab import drive
drive.mount('/content/gdrive')

boundingbox_list = []
path = '/content/gdrive/My Drive/GeoTIFF'
files = os.listdir(path)
for file in files:
  dataset = rasterio.open(f'/content/gdrive/My Drive/GeoTIFF/{file}')
  boundingbox = dataset.bounds
  boundingbox_list.append(boundingbox)

import pandas as pd
columns=['Left', 'Bottom','Right', 'Top']
boundingBoxes = pd.DataFrame(data=boundingbox_list, columns=columns)
boundingBoxes.to_csv('/content/gdrive/MyDrive/boundingBoxes')